% Sample Dissertation, Thesis, or Document %
%            for use with the              %
%  University of Arizona Thesis Class,     %
%               uathesis.cls               %
%------------------------------------------%

% We'll use the uathesis document class (duh).  The uncommented line
% below will produce a Dissertation, the others would produce a Thesis
% or a Document.  There are other options available to you like turning
% on the copyright statement and replacing the year on the title page
% with a "generated on" stamp (handy for early drafts).  To find out
% what the available options are, take a look into the uathesis.cls
% file and look for the \DeclareOption commands near the top of that
% file.
% There are five copyright options.  Copyright, no copyright, and three
% different Creative Commons licences.  Use the one you want (If you go
% Creative Commons, I (DM) think the CC-BY-ND makes the most sense)  See
% uathesis.cls for the reason why the non-commercial licenses are not
% included.
\documentclass[dissertation]{uathesis}
%\documentclass[dissertation,copyright]{uathesis}
%\documentclass[dissertation,CC-BY]{uathesis}
%\documentclass[dissertation,CC-BY-SA]{uathesis}
%documentclass[dissertation,CC-BY-ND]{uathesis}
%\documentclass[thesis]{uathesis}
%\documentclass[document]{uathesis}

% Package Usage
% These are the packages that we need
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{natbib}			% natbib is available on most systems, and is
					% terribly handy.
					
%May need to remove! Trying to fix nocite{*} biblography problem:
					% If you want to use a different Bibliography package, 
					% you should be able to, just change this
					% and the \bibliographystyle command below.  Be warned
					% that you may need to do a little hacking to get
					% the REFERENCES item to show up in your TOC.

% Compatibility with the AASTEX package 
% of the American Astronomical Society.
%\usepackage{deluxetable}		% Allows use of AASTEX deluxe tables
%\usepackage{aastex_hack}		% Allows other AASTEX functionality.

% These are other packages that you might find useful.
% For controlling the fonts, see
% http://www.math.uiuc.edu/~hartke/computer/latex/survey/survey.html
% The following is a nice font set:
%\usepackage{mathtime}			% Times for letters; Belleek math.
%
%\usepackage{amsmath}			% AMS Math (advanced math typesetting)
%\usepackage{lscape}			% Used for making fitting large tables in by putting them landscape
%\usepackage{refs}			
%
% If you are using hyper-ref (recommended), this command must go after all 
% other package inclusions (from the hyperref package documentation).
% The purpose of hyperref is to make the PDF created extensively
% cross-referenced.

%Also works! Change dvips to driverfallback=dvips.
\usepackage[driverfallback=dvips,bookmarks,colorlinks=true,urlcolor=black,linkcolor=black,citecolor=black]{hyperref}

%Works!
%\usepackage[pdftex,bookmarks,colorlinks=true,urlcolor=black,linkcolor=black,citecolor=black]{hyperref}
%HERE IS THE THING THAT NEEDS TO CHANGE TO GET LATEX TO WORK WITH RSTUDIO. USE pdftex instead of dvips.

% Set up some values.
\completetitle{Working Title: Perception of Patterns of Relative Formant Change in Reduced, Voiced, Stop Consonants}
\fullname{Megan Marie Willi}			% Grad college wants your full name here.
\degreename{Doctor of Philosophy}	% Title of your degree.

\begin{document}


% Set up the title page
\maketitlepage
{DEPARTMENT OF SPEECH, LANGUAGE, AND HEARING SCIENCES}	% Title of your department.
{2017}							

% Insert the approval form.  Note that for electronic submission
% of your Ph. D. dissertation, you must bring *two* copies of the
% approval page to your final defense.  These must be signed by
% the committee.  Make two photocopies: one for Pam and the other
% for your records.  Then, bring the two signed originals to the
% graduate college when you submit the final version of the
% dissertation to the University of Arizona.
\approval
{10 April 2017}		% Defense Date	
{Brad Story}	% Dissertation Director
{Brad Story}	% 1st committee member
{Natasha Warner}		% 2nd committee member
{Elena Plante}		% 3rd committee member
{}		% 4th committee member
{}		% 5th committee member

% Include the ``Statement by Author'' for Dissertations
\statementbyauthor
% If this is a Thesis, use the following form, with your thesis director's
% name and title in the square brackets like so (you should also omit the 
% approval form insertion above):
%\statementbyauthor[Jane M. Doe\\Professor of Chemistry]

% Include the ``Acknowledgements''
\incacknowledgements{acknowledgements}

% Include the ``Dedication''
\incdedication{dedication}

% Create a ``Table of Contents''
\tableofcontents

% Create a ``List of Figures''
\listoffigures

% Create a ``List of Tables''
\listoftables

% Include the ``Abstract''
\incabstract{abstract}

<<chunk_options, echo=FALSE>>=
# This is where we set basic knitr options.
opts_chunk$set(echo=TRUE, message=FALSE, warning = FALSE, cache = FALSE, comment="")
options(width=75) # This sets how wide the R printout can be.
@

<<load_libraries, echo=FALSE>>=
library(plyr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(lme4)
library(lsmeans)
library(car)
library(pbkrtest)
library(xtable)
library(cowplot)

@


% Include the various chapters:


%ADD: Copy/Paste Content from all 5 chapters:

%\include{Chapter_1}
\chapter{Relative Theories of Place Perception\label{chapter2}}


\section{Introduction}

The purpose of Experiment 1 is to investigate the perceptual, predictive power of relative formant deflection patterns compared to locus equation variables. The study consists of a partial re-creation of the pseudo-stop, synthetic speech experiment conducted by Lindblom and Sussman (2010) using an airway modulation model of the vocal tract area function (Story, 2005). The goal of the experiment is to 1) test the direct predictive nature of locus equation variables and relative formant deflection patterns; 2) demonstrate how relative formant deflection patterns differ from a locus equation-based theory of stop consonant perception.\footnote{Look at me!  I'm a footnote!}.

\section{Experiment 1: Relative Formant Deflection Patterns vs. Locus Equations\label{Exp1}}
\subsection{Methods}
Here are my methods.
\subsection{Results}
Here are my results. 
\section{Summary and Discussion}
Here is my summary and discussion.
\section{Conclusion}
Here is my conclusion for this chapter.


<<Exp_1_Graph, echo=FALSE, eval = TRUE, fig.cap = "Plot 1", results='asis', include=TRUE>>=

#Visualize Exp.1 Data:

#Read in Exp.1 data:
Exp1Data <- read.csv("/Users/mwilli/Documents/Spring_2017/Dissertation_Data/Experiment_1/Exp1_Summary_Data_for_Stats/Exp1_Dissertation_Data_Summary.csv")
Exp1Data$Hypothesis <- revalue(Exp1Data$Hypothesis, c("LE"="Locus Equation", "RFDP"="Relative Formant Deflection Pattern"))

#Bar Graph with error bar Exp.1:
ggplot(Exp1Data, aes(x=Hypothesis, y=Percent_Participant_Agreement, fill=Vowel_Context)) + 
    stat_summary(fun.y = mean, geom = "bar", position="dodge") + 
    stat_summary(fun.data = mean_se, geom = "errorbar", position="dodge") +ggtitle("Hypothesis Comparison") + labs(x=" Hypothesis ", y=" % Participant Agreement") +ylim(0,100)

@

<<Exp_1_Data, echo=FALSE, results='asis', include=TRUE>>=

#Stats with Mean and Standard deviation:
library(doBy)
tab <- summaryBy(Percent_Participant_Agreement ~ Hypothesis + Vowel_Context, data = Exp1Data, FUN = function(x) { c(m = mean(x), s = sd(x)) } )

library(xtable)
tab2 <- xtable(tab, caption = "Hypothesis Evaluation Results")
print(tab2)


@

%\include{chapter_3}
%\include{chapter_4}
%\include{chapter_5}

% ADD: Include the various appendices
%\appendix
%\include{appendix_A}

%Don't Change:
% Switch the spacing to single-spaced for the references
\renewcommand{\baselinestretch}{1}		% chaning the value
\small\normalsize						% switch size to make the value take

\nocite{liberman_role_1954, halle_acoustic_1957, ohman_coarticulation_1966, liberman_perception_1967, cole_toward_1974, dorman_perception_1975, stevens_invariant_1978, blumstein_acoustic_1979, blumstein_perceptual_1980, klatt_software_1980, remez_speech_1981, stevens_search_1981, walley_onset_1983, kewley-port_perception_1983, nearey_formant_1987, sussman_neural_1989, sussman_investigation_1991, remez_perceptual_1994, sussman_locus_1995, association_guidelines_1997, fruchter_perceptual_1997, story_2005, hillenbrand_open_2005, story_vowel_2009, lindblom_2010, iskarous_locus_2010, story_2010, warner_phonetic_2011, lindblom_dissecting_2012, lotto_speech_2015, lotto_frame_2015, lotto_chapter_2016}

%%%% MAKE SURE TO COPY OVER NEW Diss_Bib.bib file from Chapter_6_References. %%%%%%%%%

% Create the References list
\bibliographystyle{apa}
\bibliography{Diss_Bib}


\end{document}
